---
- name: Upload Filebeat .rpm file containing binaries from local storage
  copy:
    src: "{{ filebeat_package }}"
    dest: "/tmp/filebeat-{{ filebeat_version }}-x86_64.rpm"
  register: download_filebeat_binaries
  until: download_filebeat_binaries is succeeded